excluded:
    - Pods
    - HappyMoodBoardTests
    - HappyMoodBoardUITests
disabled_rules:
    - trailing_whitespace
    - identifier_name
    - function_body_length
line_length:
  ignores_comments: true
